poligono: poligonoTest.o poligono.o
	g++ poligonoTest.o poligono.o -o poligono

poligonoTest.o: poligonoTest.cpp
	g++ -c poligonoTest.cpp

poligono.o: poligono.cpp
	g++ -c poligono.cpp

clean:
	rm *.o poligono