triangulo: trianguloTest.o triangulo.o
	g++ trianguloTest.o triangulo.o -o triangulo

trianguloTest.o: trianguloTest.cpp
	g++ -c trianguloTest.cpp

triangulo.o: triangulo.cpp
	g++ -c triangulo.cpp

clean:
	rm *.o triangulo